### ISSUE TITLE
Checking out old outdated intelmq version

### ISSUE THREAD

**Issue by ghost** [CERT-Polska/training-materials#1]
Here:
https://github.com/CERT-Polska/training-materials/blob/ea3842954a6200b1dd2da9d1e7bf0994d505e9db/docker/intelmq/Dockerfile#L12

The RC of version 1.0.0 will be checked out. Please checkout master, that is always the current stable relase! Currently that is 1.0.2, soon 1.0.3.

**Comment by pp-** [comment]
We are using a fixed release of IntelMQ since that is the one that we tested when we developed the materials. If we change it to master, I am sure that at one point you will make changes that will break our scripts and/or some tasks in the training.

I do not see a way we can make the tools synced with their current upstream versions without re-testing everything. It might be worth updating the dependencies when IntelMQ or other tools change sufficiently to justify the testing and fixing effort.

**Comment by ghost** [comment]
We do not fix bugs for 1.0.0 anymore. If something does not work which has been fixed already, users blame intelmq nevertheless even if they are using an outdated version.

**Comment by pp-** [comment]
The question is if any of these bugs affect the training (tasks). If not, we do not really need a fixed version, IMHO. Please keep in mind, that these Docker images were created for the training, not production use.

**Comment by pp-** [comment]
These materials have been superseded by a new training: https://www.enisa.europa.eu/news/enisa-news/csirt-training-tools-new-orchestration
